#!/usr/bin/env python

import json
from subprocess import check_output

results = check_output('aws ec2 describe-images --filters "{\\"Name\\":\\"name\\",\\"Values\\":[\\"ubuntu/images/ubuntu-trusty-14.04-amd64-server-*\\"]}"', shell=True)
amis = json.loads(results.lower())

# Arbitrary starting point
most_recent = "20140101"
ami_id = ""

try:
    amis = amis["imagesset"]
except Exception as ex:
    amis = amis["images"]

for ami in amis:
    last_dash = ami["name"].rfind("-") + 1
    date = ami["name"][last_dash:]
    if date > most_recent:
        most_recent = date
        ami_id = ami["imageid"]

print ami_id
