#!/bin/bash
# Associate EIP if it's dangling

ALLOC_ID=$1

output=`/usr/local/bin/aws ec2 describe-addresses --allocation-id=$ALLOC_ID | grep InstanceId`
if [ -z "$output" ]
then
	now=$(date +"%Y-%m-%d %T")
	echo "$now - Snagging EIP"
	myID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
	`/usr/local/bin/aws ec2 associate-address --instance-id $myID --allocation-id $ALLOC_ID`
fi
